spring:
  cloud:
    gateway:
      routes:
        - id: profilesPrincipal
          uri: http://profiles
          predicates:
            - Path=/api/v1/influencers/me, /api/v1/influencers/me/followersCount, /api/v1/influencers/me/externalReferences, /api/v1/brands/me
            - Method=GET,PUT,PATCH,DELETE
          filters:
            - AddPrincipalToPathFilter
        - id: profiles
          uri: http://profiles
          predicates:
            - Path=/api/v1/influencers/*/*, /api/v1/influencers/search/**,  /api/v1/profiles/api-doc
            - Method=GET
        - id: campaign-manager
          uri: http://campaign-manager
          predicates:
            - Path=/api/v1/commands/**, /api/v1/description/**, /api/v1/comments/**, /api/v1/brief-influencers, /api/v1/briefs, /api/v1/campaigns, /api/v1/pitch-brands, /api/v1/pitches, /api/v1/ratings, /api/v1/campaign-manager/api-doc
        - id: multimedia
          uri: http://multimedia-manager
          predicates:
            - Path=/api/v1/multimedia, /api/v1/multimedia-manager/**
        - id: openapi
          uri: http://api-gateway
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /api/v1//$\{path}/api-doc
keycloak-client:
  server-url: https://auth-dev.agenadev.com/auth
