spring:
  datasource:
    url: jdbc:postgresql://database.cusdxsftolnc.eu-north-1.rds.amazonaws.com:5432/influencers-profiles?ssl=false
    username: postgres
    password: '{cipher}33816bd37a08f3269bb6b4cb20621373c14a6e54314281ac4fe1ad00b04d70b915c5d3d6e7c540ec8ea19988655a441f%'