server:
  forward-headers-strategy: framework
spring:
  data.rest.base-path: api/v1
  datasource:
    url: jdbc:postgresql://localhost:5432/influencers-profiles?ssl=false
    username: user
    password: password
  jpa:
    properties:
      hibernate:
        generate_statistics: true
        cache:
          use_second_level_cache: true
          region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
          queries: true
          ehcache:
            missing_cache_strategy: create
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
external-hal-links:
  - brief1-requests: /api/v1/brief-influencers/search/by-brand-lcs1
  - brief-requests: /api/v1/brief-influencers/search/by-brand-lcs

management:
  endpoints:
    web:
      exposure:
        include: '*'
springdoc.api-docs.path: /api/v1/profiles/api-doc
logging:
  level:
    com.agenatech: DEBUG


