server:
  port: 8086
  connection-timeout: 5s
  forward-headers-strategy: framework
spring:
  data.rest.base-path: api/v1
  datasource:
    url: jdbc:postgresql://localhost:5432/campaign-manager?ssl=false
    username: user
    password: password
  jpa:
    properties:
      hibernate:
        generate_statistics: true
        cache:
          use_second_level_cache: true
          region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
          queries: true
          ehcache:
            missing_cache_strategy: create
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
external-hal-links:
  campaigns:
    brands: /api/v1/campaigns/{?campaignId}/brands
profiles:
  url: http://localhost:8080
  ratings-url: api/v1/ratings
  brands-search-by-ids-url: api/v1/brands/search/by-ids?ids={idsList}
management:
  endpoints:
    web:
      exposure:
        include: '*'
health:
  config:
    enabled: false
springdoc.api-docs.path: /api/v1/campaign-manager/api-doc
logging:
  level:
    com.agenatech: DEBUG



