server:
  port: 8080
spring:
  datasource:
#    todo set prod endpoint
    url: jdbc:postgresql://agenatech-2.cbxabex1bwiq.eu-north-1.rds.amazonaws.com:5432/campaign-manager?ssl=false
    username: postgres
    password: '{cipher}fe810f8e3f0b32a636654b3516bf7087abe0a3ce62c4f9d037954bcc9769cebe33b02f8312f7c320caf513b0745ba113'
profiles:
  url: http://profiles
